### ISSUE TITLE
Ahoy! Firefox TODO V1

### ISSUE THREAD

**Issue by rafaelcpalmeida** [revolucaodosbytes/ahoy-firefox#1]
- [x] Initially fetch a PAC file
- [x] Fetch a new PAC file every 30 minutes
- [x] Fetch a new blocked sites list every 30 minutes
- [x] Add the button to view the blocked sites list
- [x] Dynamic version shown on the popup
- [x] Send statistics to the API

**Comment by rafaelcpalmeida** [comment]
List updated

**Comment by rafaelcpalmeida** [comment]
V1 Done

**Comment by rafaelcpalmeida** [comment]
Follow up #2
